config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      get 'generate_qr_code'
      get 'search'
    end
  end
  post '/generate_all_qrs', to: 'articles#generate_all_qrs', as: 'generate_all_qrs'


  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :photo

  validates :price, numericality: { greater_than: 0 }
  validates :code, format: { with: /\A\d{8}\z/, message: "should be a 8-digit number" }
  validates :code, uniqueness: true
  validates_presence_of :photo, message: "must exist"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout "show_layout", only: [:show]
  before_action :authenticate_user!, except: [:show]

  before_action :set_article, only: %i[ show edit update destroy generate_qr_code ]

  def index
    @query = params[:search]
    # flash[:alert] = "Welcome to the home page!"

    if @query.present?
      # Check if the search query matches the format of an 8-digit number
        @articles = Article.where("code LIKE ?", "%#{@query}%")
    else
      
      @articles = Article.all
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
 
  def generate_qr_code
    image = generate_qr_with_article(@article)
    send_data image.to_blob, type: "image/png", disposition: "inline"
  end
  


  def generate_all_qrs
    selected_ids = params['selectedIds']
    qr_images = []
    selected_ids.each do |article_id|
      article = Article.find(article_id)
      qr_code = generate_qr_with_article(article)
      qr_images << qr_code
    end
  
    merged_qr_code_path = merge_qr_codes(qr_images, qr_images.length)

    # Send the merged QR code image as a response
    send_file merged_qr_code_path, type: 'image/png', disposition: 'inline'
  end
  
  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private
  
  
  def generate_qr_with_article(article) 
    data = article_url(article)
    qr = RQRCode::QRCode.new(data, size: 8, level: :h)
    qr_code = qr.as_png(size: 130)
    image = MiniMagick::Image.read(qr_code.to_s)
    text = "#{article.code}"
    text_size = 10
    text_x = (image.width / 2) - (text_size * text.length / 2)  - 20
    text_y = (image.height / 2) - (text_size / 2) - 2
    image.combine_options do |c|
      c.gravity "center"
      c.fill "black"
      c.stroke "none"
      c.pointsize text_size
      c.draw "text #{text_x},#{text_y} '#{text}'"
    end
    image  
  end
  def merge_qr_codes(qr_images, article_count)
    grid_columns = Math.sqrt(article_count).ceil
    grid_rows = (article_count / grid_columns.to_f).ceil
    timestamp = Time.now.strftime("%Y%m%d%H%M%S")
    merged_qr_code_path = Rails.root.join('public', "qr_codes_#{timestamp}.png")
    MiniMagick::Tool::Montage.new do |montage|
      montage.geometry '100x100'  # Define the size of each tile
      montage.tile "#{grid_columns}x#{grid_rows}"  # Define the grid layout

      # Append all the QR code images to the montage
      qr_images.each do |qr_image|
        montage << qr_image.path
      end

      # Set the output path for the merged QR code image
      montage << merged_qr_code_path
    end

    merged_qr_code_path
  end
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :code, :photo, :price, :promo_price, :on_promo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        flash[:notice] = "Welcome to the home page!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
  
<div id="<%= dom_id(article) %>" 
    style="background: white"
class="card relative  flex flex-col  bg-white rounded-lg border shadow-xl bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] ">

  <div  data-article-id="<%= article.id %>" class="selectable-card relative overflow-hidden bg-cover bg-no-repeat flex-1 h-64" style="max-height: 200px" data-te-ripple-init data-te-ripple-color="light">
      <input type="checkbox" class="absolute top-0 left-0 m-2 checked:border-blue-600 " style="z-index: 10;" />

    <% if article.photo.attached? %>
      <%= image_tag article.photo, class: "rounded-t-lg object-fill", width: 200, height: 200 %>
    <% else %>
      <p class="text-xl text-gray-600">No photo available</p>
    <% end %>
    <img src="<%= generate_qr_code_article_path(article, format: :svg) %>" class="w-20 absolute top-0 right-0 rounded-t-lg" alt="QR Code for Article" height="100" width="100" />
  </div>
  

  <div class="px-4 py-2">
    <h5 class="mb-2 text-xl font-medium leading-tight text-neutral-800 ">
      <%= article.name %>
    </h5>

    <p class="text-lg text-neutral-600 ">
      <strong>Code:</strong> <%= article.code %>
    </p>
    <p class="text-lg text-neutral-600 ">
      <strong>Price:</strong> <%= article.price %> DH
    </p>
    <% if article.on_promo && article.promo_price %>
      <p class="text-lg text-neutral-600 ">
        <strong>Promo Price:</strong> <%= article.promo_price %> DH
      </p>
    <% elsif article.on_promo && article.promo_price.nil? %>
      <p class="text-lg text-neutral-600 ">This article is on promo, but no promo price set.</p>
    <% else %>
      <p class="text-lg text-neutral-600 ">This article is not on promo.</p>
    <% end %>
    <% if action_name != "show" %>
      <div class="flex pt-2 space-x-2">
        <%= link_to "Show ", article, class: "btn-sm" %>
        <%= link_to "Edit ", edit_article_path(article), class: "btn-sm" %>
<%= link_to "Download QR code", generate_qr_code_article_path(article, format: :png), target: "_blank", class: "btn-sm", download: "#{article.name.split(' ')[0, 5].join('_').parameterize}#{article.code}_sm.png" %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :code %>
    <%= form.text_field :code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :promo_price %>
    <%= form.text_field :promo_price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

 

  <div class="inline">
    <%= form.submit class: "btn-sm" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Show this article", @article, class: "btn-sm" %>
  <%= link_to "Back to articles", articles_path, class: "btn-sm" %>
</div>

app/views/articles/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Articles</h1>
    <div>    <%= link_to "New article", new_article_path, class: "btn-sm" %>
      <button class="btn-sm" id="select-all">Select All</button>
      <button class="btn-sm hidden" id="qr-all" >Download ALL QR</button>
    </div>
  </div>
  <br/>
  <%= form_tag(articles_path, method: :get, class: "") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <% end %>
  <br/>
  <div id="articles" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
    <% if @articles.any? %>
      <%= render @articles %>
    <% else %>
      <p>No articles found.</p>
    <% end %>
  </div>
</div>

<style>
  .card_selected {
    border: 2px solid blue !important;
    /* Change the border to indicate selection */
  }
</style>


<script>
  document.addEventListener("DOMContentLoaded", function () {
  var all_selected = false;
  const csrfToken = "<%= form_authenticity_token %>";

  var selectedIds = []; // To store the selected article IDs

  const cards = document.querySelectorAll(".selectable-card");
  const selectAllBtn = document.getElementById("select-all");
  const downloadAllQrBtn = document.getElementById("qr-all");

  // Helper function to update the selected IDs array
  function updateSelectedIds() {
    selectedIds = [];
    cards.forEach((card) => {
      const checkbox = card.querySelector("input[type=checkbox]");
      if (checkbox.checked) {
        const articleId = card.getAttribute("data-article-id");
        selectedIds.push(articleId);
      }
    });
    if(selectedIds.length > 0) {
      downloadAllQrBtn.classList.remove("hidden");
    }else{
      downloadAllQrBtn.classList.add("hidden");
    }
  }



  downloadAllQrBtn.addEventListener("click", function (event) {
    event.preventDefault();
    console.log(selectedIds);

    // Prepare the JSON data
    const jsonData = JSON.stringify({  selectedIds });

    // Make a POST request to the generate_all_sm endpoint
    fetch('/generate_all_qrs', {
      method: 'POST',
      
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': csrfToken, // Include the CSRF token here

      },
      body: jsonData
    })
      .then(response => {
        if (response.ok) {
          // Success: Download the generated QR codes
          response.blob().then(blob => {
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'merged_qr_codes.png';
            a.style.display = 'none';
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
          });
        } else {
          // Handle errors
          console.error('Failed to generate QR codes:', response.status, response.statusText);
        }
      })
      .catch(error => {
        console.error('Error:', error);
      });
  });

  selectAllBtn.addEventListener("click", function (event) {
    all_selected = !all_selected;
    cards.forEach((card) => {
      const checkbox = card.querySelector("input[type=checkbox]");
      checkbox.checked = all_selected;
      if (!all_selected) {
        card.parentElement.classList.remove("card_selected");
        selectAllBtn.textContent = "Select All";
     
      } else {
        card.parentElement.classList.add("card_selected");
        selectAllBtn.textContent = "Deselect All";
      }
    });

    // Update the selected IDs
    updateSelectedIds();
  });

  cards.forEach((card) => {
    const checkbox = card.querySelector("input[type=checkbox]");

    if (checkbox.checked) {
      card.parentElement.classList.add("card_selected");
    } else {
      card.parentElement.classList.remove("card_selected");
    }

    card.addEventListener("click", function (event) {
      event.preventDefault();
      checkbox.checked = !checkbox.checked;
      card.parentElement.classList.toggle("card_selected");
      updateSelectedIds();
    });
  });
});

</script>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Product</h1>

  <%= render "form", article: @article %>

  <%= link_to "Back to articles", articles_path, class: "btn-sm" %>
</div>

app/views/articles/show.html.erb
<div class="flex items-center border-b-2 border-black bg-white px-2 md:px-4 justify-between" style="background: black; color:white; padding: 1em">
  <img
    src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Bim_%28company%29_logo.svg/1200px-Bim_%28company%29_logo.svg.png"
    class="md:w-22 w-20" alt="Bim Logo" />
      <% if @article.name.split.size.between?(5, 7) %>
      <h1 class="ml-auto font-bold text-2xl md:text-5xl px-2">
        <span class="font-semibold text-2xl md:text-5xl">
          <%= @article.name.split(" ").first(4).join(" ") %>
        </span>
        <span class="font-semibold text-xl md:text-3xl">
          <%= @article.name.split(" ").drop(4).join(" ") %>
        </span>
      </h1>
    <% else %>
      <h1 class="ml-auto font-bold text-xl px-2">
      <%= @article.name.split(" ").first(4).join(" ") %>
      </h1>
    <% end %>
    
    

</div>
<!-- Body -->
<div class="w-full flex-grow justify-center gap-2 bg-slate-100">
  <div class="relative mx-auto my-8 max-w-lg md:mt-32">
    <div class="absolute right-4 top-4 space-x-1">
<% if @article.promo_price %>
    <div class="text-center">
    <p class="text-2xl font-bold text-red-600">
      <s><%=  sprintf("%.2f", @article.price) %> DH</s>
    </sup>

    </p>
    <p class="rounded-lg bg-red-600 px-3 py-1 text-2xl font-bold text-white md:text-3xl">
  <%= @article.promo_price.to_i %>,
    <sup class="text-sm md:text-base strock">
      <%= sprintf("%02d", (@article.promo_price - @article.promo_price.to_i) * 100) %> DH
    </sup>    </p>
  </div>
<% else %>
  <p class="rounded-lg bg-red-600 px-3 py-1 text-2xl font-bold text-white md:text-3xl">
    <%= @article.price.to_i %>,
    <sup class="text-sm md:text-base strock">
      <%= sprintf("%02d", (@article.price - @article.price.to_i) * 100) %> DH
    </sup>
  </p>
<% end %>

      <span class="absolute -bottom-5 right-0 bg-yellow-400 text-right text-sm"><%= @article.code %></span>
    </div>
    <% if @article.photo.attached? %>
    <%= image_tag @article.photo, class: "w-full object-cover" %>
  <% else %>
    <p class="text-xl text-gray-600">No photo available</p>
  <% end %>
  </div>

  <p class="ml-auto font-bold text-xl w-fit px-4">
      <%= @article.name %>
      </p>
</div>

app/views/home/index.html.erb
<h1>ticker tracker</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketScanner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>


  </head>
  <style>
      html {
        height: 100%;
      }
      body {
        min-height: 100%;
        display: flex;
        flex-direction: column;
      }
      .flex-grow {
        flex-grow: 1;
      }
      .bg-black{
        background-color: black
      }
      .text-white {
        color: white
      }
      .bg-red-600{
        background-color: #e30713
      }
      .bg-white{
        background-color: white !important;
      }
      .bg-red-700{
        background-color: #e30713
        
      }
      .text-white{
        color: white !important;
      }
      .bg-yellow-400{
        background-color: #facc15
      }
      .bg-image {
        background-image: url('/bg-bim.svg'); /* Path to your SVG in the "public" folder */
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed; /* Optional - keeps the background fixed while scrolling */
        background-position: center center;
        min-height: 100%;
      }
    </style>

  <body class="flex flex-col bg-image">
    <%= render "/partials/alert" %>
    <%= render "/partials/notice" %>
    <%= render "/partials/nav" %>
    
    <main class="container max-w-8xl mx-auto mt-10 flex-grow bg-slate-800">
      <%= yield %>
    </main>
    <footer class="w-full bg-black p-4 text-white md:p-8 mt-auto" >
      <div class="container mx-auto">
        <div class="flex flex-col items-center justify-between gap-4 md:flex-row">
          <!-- Your footer content goes here -->
          <div class="">
            <a href="#"> <img src="https://www.bim.ma/templates/page/bimtr/css/images/bottom_logo.png" alt="" /> </a>
          </div>
          <div class="flex flex-col md:flex-row">
            <ul>
              <li>
                <a href="https://www.bim.ma/contenu/1/philosophie-de-bim.aspx">Philosophie de BİM<span>مبادئ بيم</span></a>
              </li>
              <li>
                <a href="https://www.bim.ma/contenu/7/présentation-du-produit.aspx">Présentation du Produit <span>عرض المنتج</span></a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="https://www.bim.ma/contenu/3/assurance-qualité.aspx">Assurance Qualité <span>ضمان الجودة</span> </a>
              </li>
              <li>
                <a href="https://www.bim.ma/contenu/5/carrière-chez-bim.aspx">Carrière chez BİM<span>فرص التوظيف في BIM </span></a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="https://www.bim.ma/contenu/2/magasins.aspx">Magasins<span>متاجرنا</span></a>
              </li>
              <li>
                <a href="https://www.bim.ma/contenu/10/formulaire-de-réclamation.aspx">Formulaire de réclamation<span>استمارة الشكوى</span></a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="https://www.bim.ma/contenu/4/nous-contacter.aspx">Nous Contacter<span>للاتصال بنا </span></a>
              </li>
              <li>
                <a href="https://www.bim.ma/contenu/11/vous-etes-propriétaire-d-un-local-que-vous-voulez-louer.aspx">Formulaire location magasin<span> استمارة كراء محل تجاري</span></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/show_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketScanner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
 <style>
      html {
        height: 100%;
      }
      body {
        min-height: 100%;
        display: flex;
        flex-direction: column;
      }
      .flex-grow {
        flex-grow: 1;
      }
      .bg-black{
        background-color: black
      }
      .text-white {
        color: white
      }
      .bg-red-600{
        background-color: #e30713
      }
      .bg-yellow-400{
        background-color: #facc15
      }
    </style>
  <body class="flex flex-col bg-gray-100 relative">
    <%= render "/partials/alert" %>
    <%= render "/partials/notice" %>
    
      <%= yield %>
    
     <div class="w-full bg-black p-4 text-white md:p-8" >
      <div class="container mx-auto">
        <div class="flex flex-col items-center justify-between gap-4 md:flex-row">
          <!-- Your footer content goes here -->
          <div class="">
            <a href="#"> <img src="https://www.bim.ma/templates/page/bimtr/css/images/bottom_logo.png" alt="" /> </a>
          </div>
          <div class="flex flex-col md:flex-row">
            <ul>
              <li>
                <a href="www.bim.ma/contenu/1/philosophie-de-bim.aspx">Philosophie de BİM<span>مبادئ بيم</span></a>
              </li>
              <li>
                <a href="www.bim.ma/contenu/7/présentation-du-produit.aspx">Présentation du Produit <span>عرض المنتج</span></a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="www.bim.ma/contenu/3/assurance-qualité.aspx">Assurance Qualité <span>ضمان الجودة</span> </a>
              </li>
              <li>
                <a href="www.bim.ma/contenu/5/carrière-chez-bim.aspx">Carrière chez BİM<span>فرص التوظيف في BIM </span></a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="www.bim.ma/contenu/2/magasins.aspx">Magasins<span>متاجرنا</span></a>
              </li>
              <li>
                <a href="www.bim.ma/contenu/10/formulaire-de-réclamation.aspx">Formulaire de réclamation<span>استمارة الشكوى</span></a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="www.bim.ma/contenu/4/nous-contacter.aspx">Nous Contacter<span>للاتصال بنا </span></a>
              </li>
              <li>
                <a href="www.bim.ma/contenu/11/vous-etes-propriétaire-d-un-local-que-vous-voulez-louer.aspx">Formulaire location magasin<span> استمارة كراء محل تجاري</span></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/partials/_alert.html.erb
<% if alert %>
  <div id="alert-pop"
  style="z-index: 1000; background: white !important; color: #e30713 !important; top: 1em;"
    
  class=" absolute right-4 pointer-events-auto mx-auto mb-4 w-96 max-w-full rounded-lg bg-danger-100 bg-clip-padding text-sm text-danger-700 shadow-lg shadow-black/5 data-[te-toast-show]:block data-[te-toast-hide]:hidden" id="static-example" role="alert" aria-live="assertive" aria-atomic="true" data-te-autohide="true" data-te-toast-init data-te-toast-show>
    <div class="flex items-center justify-between rounded-t-lg border-b-2 border-danger-200 bg-danger-100 bg-clip-padding px-4 pb-2 pt-2.5 text-danger-700">
      <p class="flex items-center font-bold text-danger-700">
        <%= alert %>
      </p>
      <div class="flex items-center">
        <button id="alert-close-btn" type="button" class="ml-2 box-content rounded-none border-none opacity-80 hover:no-underline hover:opacity-75 focus:opacity-100 focus:shadow-none focus:outline-none" data-te-toast-dismiss aria-label="Close">
          <span class="w-[1em] focus:opacity-100 disabled:pointer-events-none disabled:select-none disabled:opacity-25 [&.disabled]:pointer-events-none [&.disabled]:select-none [&.disabled]:opacity-25">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </span>
        </button>
      </div>
    </div>
  </div>

<script>
  // JavaScript code to close the alert and hide it after 1 second
  document.addEventListener("DOMContentLoaded", function () {
        const alertElement = document.getElementById("alert-pop");
        const closeButton = document.getElementById("alert-close-btn");

        closeButton.addEventListener("click", function () {
          alertElement.style.display = "none";
        });

        if (alertElement.getAttribute("data-te-autohide") === "true") {
          setTimeout(function () {
            alertElement.style.display = "none";
          }, 3000);
        }
      });
</script>

<% end %>

app/views/partials/_nav.html.erb
  <div class="flex w-full flex-wrap items-center justify-between p-3  border-b" style="border-bottom: 1px solid; background: black; color:white">
    <!-- Collapsible navigation container -->
    <div class="items-center " >
      <!-- Logo -->
      <a
        class="mb-4 ml-2 mr-5 mt-3 flex items-center text-white hover:text-white focus:text-white lg:mb-0 lg:mt-0"
        href="/">
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Bim_%28company%29_logo.svg/1200px-Bim_%28company%29_logo.svg.png"
          alt="BIM Logo"
          class="w-20"
          loading="lazy" />
      </a>
    </div>

    <%= render '/partials/user_card' %>
  </div>

app/views/partials/_user_card.html.erb
<% if user_signed_in? %>
  <div class="flex items-center">
    <span class="text-sm">Welcome <span class="font-semibold hover:underline"><%= current_user.name %></span></span>
    <%= link_to "profile", edit_user_registration_path, class: "btn-sm ml-2" %>
  </div>
<% else %>
  <div class="ml-auto">
  <%= link_to "Sign up", new_user_registration_path, class: "btn-sm" %> 
  <%= link_to "Login", new_user_session_path, class: "btn-sm ml-2" %>
  </div>
<% end %>